@IELTS_API_HostAddress = https://localhost:7290

POST {{IELTS_API_HostAddress}}/api/tests
Content-Type: application/json

{
  # "name": "IELTS Test 2019",
  # "description": "The IELTS Test in 2019",
  # "bandLevel": 6.5
}

###

GET {{IELTS_API_HostAddress}}/api/tests

###

@id=1
GET {{IELTS_API_HostAddress}}/api/tests/{{id}}

###

PUT {{IELTS_API_HostAddress}}/api/tests/1
Content-Type: application/json

{
  # "id": 1,
  # "name": "IELTS Test 2017",
  # "description": "The IELTS Test in 2017",
  # "bandLevel": 7.5
}

###

DELETE {{IELTS_API_HostAddress}}/api/tests/1

###
