server {
    listen 80;
    # Thư mục chứa file sau khi build
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Dòng quan trọng nhất!
        # Nếu không tìm thấy file, nó sẽ trả về index.html để React Router xử lý
        try_files $uri $uri/ /index.html;
    }
}